EQR_Go2/EQR_Go2/Controllers/AddEntryController.cs
using EQR_Go2.Models;
using EQR_Go2.Views.Shared;
using Massive.SQLite;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EQR_Go2.Controllers
{
    public class AddEntryController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.CurMenu = "addentry";
            ViewBag.OpSuccessMsg = "";
            ViewBag.HeaderMsg = "Going on a help mission? Help channelize the relief efforts by letting others know about your trip.";
            return View();
        }

        public ActionResult Suggest()
        {
            ViewBag.CurMenu = "suggest";
            return RedirectToAction("Index");
        }


        [HttpPost]
        public ActionResult Index(FormCollection fc)
        {
            ViewBag.CurMenu = "addentry";
            ViewBag.HeaderMsg = "Going for help ? Fill up the form below to help others know what needs to be done";
            var teamTable = new Team();
            var newTeam = teamTable.CreateFrom(fc);
            var teamId = teamTable.Insert(newTeam);
            // parse member list from fc
            var personTable = new Person();
            foreach (var mKey in fc.AllKeys.Where(k => k.StartsWith("m_")))
            {
                string index = mKey.Split(new string[] { "_" }, StringSplitOptions.RemoveEmptyEntries)[1];
                var p = new { Name = fc[mKey], Contact = fc["mn_" + index], Role = FixedObjects.Role[FixedObjects.RoleList.Volunteer], TeamID = teamId };
                personTable.Insert(p);
            }


            var teamCommodityDetailsTable = new TeamCommodityDetails();
            // parse original commodity details from fc
            foreach (var cKey in fc.AllKeys.Where(k => k.StartsWith("oc_")))
            {
                string index = cKey.Split(new string[] { "_" }, StringSplitOptions.RemoveEmptyEntries)[1];
                long curCount = 0;
                long.TryParse(fc["occount_" + index],out curCount);
                var p = new { CommodityID = long.Parse(fc[cKey]), Count = curCount, TeamID = teamId };
                teamCommodityDetailsTable.Insert(p);
            }

            // parse newly added commodity details from fc
            foreach (var cKey in fc.AllKeys.Where(k => k.StartsWith("c_")))
            {
                string index = cKey.Split(new string[] { "_" }, StringSplitOptions.RemoveEmptyEntries)[1];
                var p = new { CommodityID = long.Parse(fc[cKey]), Count = long.Parse(fc["ccount_" + index]), TeamID = teamId };
                teamCommodityDetailsTable.Insert(p);
            }

            ViewBag.OpSuccessMsg = "Details successfully submitted.";
            return View();
        }
        public ActionResult New()
        {

            return View();
        }
    }
}

EQR_Go2/EQR_Go2/Views/AddEntry/Index.cshtml
@using EQR_Go2.Views.Shared;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_EntryLayout.cshtml";
    int comCounter = 0;
}
<script src="~/Scripts/Custom/AddCommodity.js"></script>
<script>
    $().ready(function () {
        var msg = "@ViewBag.OpSuccessMsg";
        if(msg.length > 0)
        {
            alert(msg);
        }
    });
</script>
@using (Html.BeginForm("Index", "AddEntry", FormMethod.Post,new { id="frmEntry"}))
{
    @Html.AntiForgeryToken()
    <div id="errors"></div>
    <div class="row">
        <div class="six columns"><label for="TeamName">Team Name</label></div>
        <div class="six columns">
            <input type="text" name="TeamName" id="TeamName" />
        </div>
    </div>

    <div class="row">
        <div class="six columns"><label for="memCount">Member Count</label></div>
        <div class="six columns">
            <input type="number" name="memCount" id="memCount" />
        </div>
    </div>

    <div class="row">
        <div class="six columns"><label for="primaryContact">Primary Contact</label></div>
        <div class="six columns">
            <input type="text" name="primaryContact" id="primaryContact" />
        </div>
    </div>

    <div class="row">
        <div class="six columns"><label for="DepartureFrom">Departure From</label></div>
        <div class="six columns">
            <input type="text" name="DepartureFrom" id="DepartureFrom" />
        </div>
    </div>


    <div class="row">
        <div class="six columns"><label for="Destination">Destination</label></div>
        <div class="four columns">
            @Html.DropDownList("Destination", FixedObjects.SiteList.Select(s => new SelectListItem { Text = s.Name, Value = s.Name }), new { id="Destination"})
        </div>
        <div class="two columns">
            <button id="addNewDestination" title="Add new destination">Add New</button>
        </div>
    </div>

    <div class="row">
        <div class="six columns">
            <label for="DepartureOn">Departing on</label>
            <input type="text" name="DepartureOn" id="DepartureOn" data-role="date" />
        </div>
        <div class="six columns">
            <label for="ETA">Estimated Arrival on</label>
            <input type="text" name="ETA" id="ETA" data-role="date" />
        </div>
    </div>


    <div class="row">
        <div class="row"><label for="TeamMembers">Crew Detail(more detail you add, easier it is for others to contact you and your team)</label></div>
        <div class="row" id="teamMembers"></div>
        <div class="row">
            <button id="addNewMember" title="Add a team member" type="button">Add Team Member</button>
        </div>
    </div>

    <div class="row">
        <div class="row"><h4>What commodities are you taking with yourself ? </h4></div>
        <div id="existingCommodities" class="row">
            @foreach (var c in FixedObjects.CommodityList)
            {
                <div class="row">
                    <div class="six columns"><label for="oc_count__@(comCounter++)" style="text-transform:capitalize;" class="cname">@c.Name</label></div>
                    <div class="six columns">
                        <input type="hidden" name="oc_@comCounter" value="@c.ID" />
                        <input type="number" name="occount_@comCounter" id="occount_@comCounter" />
                    </div>
                </div>
            }
        </div>
        <div id="newCommodity">
            <button id="addNewCommodity">New Mentionable Commodity</button>
        </div>
    </div>

    <button type="submit" class="button-primary">Save Trip Details</button>

}